# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0002_auto_20160703_2325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
