# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-21 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg', '0003_auto_20161021_2018'),
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='users',
            field=models.ManyToManyField(to='loginreg.User'),
        ),
    ]
